const char *html =
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "    <title>ESP webpage</title>\n"
    "    <style>\n"
    "        html{\n"
    "            font-family: Helvetica;\n"
    "            display: inline-block;\n"
    "            margin: 0px auto;\n"
    "            text-align: center;\n"
    "        }\n"
    "    </style>\n"
    "</head>\n"
    "<body>\n"
    "    <h1>ESP8266 Web Server \"yeah\"</h1>\n"
    "</body>\n"
    "</html>\n"
;